name: Retrieve latest cache of dependencies, if cache exists and is valid
description: If node_modules tar file exists in S3, copies it and unzips in working dir
runs:
  using: "composite"
  steps:
    - name: Print environment variables for debugging
      run: env
    - name: Ensure script is executable
      run: chmod +x "${{ github.action_path }}/harrier-cache-load.sh"
      shell: bash
    - name: Run cache-load, to retrieve latest cache if valid
      run: "${{ github.action_path }}/harrier-cache-load.sh"
      shell: bash
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
