name: Retrieve Latest Cache of Dependencies
description: "This action retrieves and unzips the latest cached dependencies from S3 if a valid node_modules tar file exists, saving installation time."
author: Harrier Team

runs:
  using: "composite"
  steps:
    - name: Run Cache Load Script
      run: ./harrier-cache-load.sh
      shell: bash
