name: Retrieve latest cache of dependencies, if cache exists and is valid
description: If node_modules tar file exists in S3, copies it and unzips in working dir
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run cache-load, to retrieve latest cache if valid
      run: harrier-cache-load.sh
      shell: bash
